#!/user/bin/env bash

echo '-------------------------------------------------------------------------------'
echo '     ____               ____           __        ____   ___              __    '
echo '    / __ \________     /  _/___  _____/ /_____ _/ / /  /   |  __________/ /_   '
echo '   / /_/ / ___/ _ \    / // __ \/ ___/ __/ __ `/ / /  / /| | / ___/ ___/ __ \  '
echo '  / ____/ /  /  __/  _/ // / / (__  ) /_/ /_/ / / /  / ___ |/ /  / /__/ / / /  '
echo ' /_/   /_/   \___/  /___/_/ /_/____/\__/\__,_/_/_/  /_/  |_/_/   \___/_/ /_/   '
echo '                                                                               '
echo '-------------------------------------------------------------------------------'

echo "Setar TIMEZONE"
ln -sf /usr/share/zoneinfo/America/Campo_Grande /etc/localtime
hwclock --systohc

echo "Definir localização e idioma"
sed -i 's:#pt_BR.UTF-8 UTF-8:pt_BR.UTF-8 UTF-8 ; s:#pt_BR ISO-8859-1:pt_BR ISO-8859-1': /etc/locale.gen
locale-gen
echo "LANG=pt_BR.UTF-8" >> /etc/locale.conf
echo "KEYMAP=/usr/share/kbd/keymaps/i386/qwerty/br-abnt2.map.gz" >> /etc/vconsole.conf

echo "Configurar Internet"
echo "arch" >> /etc/hostname
echo -e "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\tarch.localdomain arch" >> /etc/hosts

echo "Update Pacman System"
pacman -Syyuu

echo "Definir senha de root"
passwd

echo "Configure o boot da máquina"
exit 0